### PR TITLE
UPDATE LIBS: Update Parse, Bolts and Facebook Libraries

### PR DESCRIPTION
**Pull request by swami701**
This Pull request upgrades the following libraries
- *Parse* 1.12 -> 1.15.1
- *Facebook* 4.10 -> 4.24.0 (Uses the Graph API Version [2.9](https://github.com/facebook/facebook-ios-sdk/blob/92c28b14cea7ee00d5f6da0a90c624d304a36c46/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit.h#L48))
- *Bolts* 1.6 -> 1.8.4

Please help me to review and merge.

Thank you.

### CODE REVIEW

**Comment by swami701** [comment]
@flovilmart Can you help me to review and merge this commit? Thank you.

**Comment by flovilmart** [comment]
You probably need to update the code so it works with those most recent versions

**Comment by swami701** [comment]
@flovilmart I tried the same commands in the `.travis.yml` file in my local machine. It seems it's passing all the steps.

My ruby, bundler, rake, pod, xcode versions
Ruby
```
➜  ParseFacebookUtils-iOS git:(master) ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
```
bundler 
```
➜  ParseFacebookUtils-iOS git:(master) bundle --version
Bundler version 1.15.3
```
rake
```
➜  ParseFacebookUtils-iOS git:(master) rake --version
rake, version 11.2.2
```

Pod
```
➜  ParseFacebookUtils-iOS git:(master) pod --version
1.0.1
```
Xcode
```
➜  ParseFacebookUtils-iOS git:(master) xcodebuild -version
Xcode 8.3.3
Build version 8E3004b
```

And I executed all the below commands in order
```
➜  ParseFacebookUtils-iOS git:(master) export LC_CTYPE=en_US.UTF-8
➜  ParseFacebookUtils-iOS git:(master) export LANG=en_US.UTF-8
➜  ParseFacebookUtils-iOS git:(master) bundle install
➜  ParseFacebookUtils-iOS git:(master) pod repo update --silent
➜  ParseFacebookUtils-iOS git:(master) pod install
➜  ParseFacebookUtils-iOS git:(master) set -o pipefail
➜  ParseFacebookUtils-iOS git:(master) xcodebuild test -workspace ParseFacebookUtils.xcworkspace -sdk iphonesimulator -scheme ParseFacebookUtilsV4-iOS -configuration Debug -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty
➜  ParseFacebookUtils-iOS git:(master) pod lib lint --use-libraries ParseFacebookUtilsV4.podspec
➜  ParseFacebookUtils-iOS git:(master) bundle exec rake package:frameworks
```


It seems everything is good.
Following are the logs for that
```
➜  ParseFacebookUtils-iOS git:(master) export LC_CTYPE=en_US.UTF-8
➜  ParseFacebookUtils-iOS git:(master) export LANG=en_US.UTF-8
➜  ParseFacebookUtils-iOS git:(master) bundle install
Using rake 11.2.2
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.0
Using thread_safe 0.3.5
Using bundler 1.15.3
Using claide 1.0.0
Using fuzzy_match 2.0.4
Using nap 1.1.0
Using cocoapods-deintegrate 1.0.0
Using cocoapods-downloader 1.1.0
Using cocoapods-search 1.0.0
Using cocoapods-stats 1.0.0
Using netrc 0.7.8
Using cocoapods-try 1.1.0
Using colored 1.2
Using escape 0.0.4
Using fourflusher 0.3.2
Using molinillo 0.4.5
Using naturally 2.1.0
Using rouge 1.11.1
Using tzinfo 1.2.2
Using cocoapods-plugins 1.0.0
Using cocoapods-trunk 1.0.0
Using xcpretty 0.2.2
Using activesupport 5.0.0
Using cocoapods-core 1.0.1
Using xcodeproj 1.2.0
Using cocoapods 1.0.1
Bundle complete! 4 Gemfile dependencies, 29 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
➜  ParseFacebookUtils-iOS git:(master) pod repo update --silent
➜  ParseFacebookUtils-iOS git:(master) pod install
Analyzing dependencies
Downloading dependencies
Using OCMock (3.3.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `ParseFacebookUtilsV4-UnitTests` to `Pods/Target Support Files/Pods-ParseFacebookUtilsV4-UnitTests/Pods-ParseFacebookUtilsV4-UnitTests.release.xcconfig` or include the `Pods/Target Support Files/Pods-ParseFacebookUtilsV4-UnitTests/Pods-ParseFacebookUtilsV4-UnitTests.release.xcconfig` in your build configuration (`Configurations/ParseFacebookUtilsV4-UnitTests.xcconfig`).
➜  ParseFacebookUtils-iOS git:(master) set -o pipefail
➜  ParseFacebookUtils-iOS git:(master) xcodebuild test -workspace ParseFacebookUtils.xcworkspace -sdk iphonesimulator -scheme ParseFacebookUtilsV4-iOS -configuration Debug -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty

2017-09-19 10:49:06.414 xcodebuild[8704:77573]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Logs/Test/12C1A2FC-A0CA-4801-A3F9-C136777887F9/Session-ParseFacebookUtilsV4-UnitTests-2017-09-19_104906-wKd9ma.log
2017-09-19 10:49:06.414 xcodebuild[8704:77540] [MT] IDETestOperationsObserverDebug: (D0D5B789-35D5-44F7-8934-4B649F2444FA) Beginning test session ParseFacebookUtilsV4-UnitTests-D0D5B789-35D5-44F7-8934-4B649F2444FA at 2017-09-19 10:49:06.414 with Xcode 8E3004b on target <DVTiPhoneSimulator: 0x7fda8a9f8ad0> {
		SimDevice: SimDevice : iPhone 4s (637470EF-338E-493F-9795-7BBA20652651) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-4s } runtime={ SimRuntime : 8.4 (12H141) - com.apple.CoreSimulator.SimRuntime.iOS-8-4 }
} (8.4 (12H141))
▸ Building ParseFacebookUtils/ParseFacebookTestApplicationV4 [Debug]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling main.m
▸ Linking ParseFacebookTestApplicationV4
▸ Generating 'ParseFacebookTestApplicationV4.app.dSYM'
▸ Touching ParseFacebookTestApplicationV4.app
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/ParseFacebookTestApplicationV4.app
▸ Building ParseFacebookUtils/ParseFacebookUtilsV4-iOS [Debug]
▸ Check Dependencies
▸ Processing Info-iOS.plist
▸ Running script 'Fetch latest Dependencies'
▸ Running script 'Generate Localizable Strings'
▸ Copying PFFacebookUtils.h
▸ Copying ParseFacebookUtilsV4.h
▸ Compiling PFFacebookAuthenticationProvider.m
▸ Compiling PFFacebookUtils.m
▸ Compiling PFFacebookMobileAuthenticationProvider.m
▸ Compiling PFFacebookPrivateUtilities.m
▸ Copying Localizable.strings
▸ Touching ParseFacebookUtilsV4.framework
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/ParseFacebookUtilsV4.framework
▸ Building Pods/OCMock [Debug]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling NSInvocation+OCMAdditions.m
▸ Compiling NSMethodSignature+OCMAdditions.m
▸ Compiling NSNotificationCenter+OCMAdditions.m
▸ Compiling NSObject+OCMAdditions.m
▸ Compiling NSValue+OCMAdditions.m
▸ Compiling OCClassMockObject.m
▸ Compiling OCMArg.m
▸ Compiling OCMArgAction.m
▸ Compiling OCMBlockArgCaller.m
▸ Compiling OCMBlockCaller.m
▸ Compiling OCMBoxedReturnValueProvider.m
▸ Compiling OCMConstraint.m
▸ Compiling OCMExceptionReturnValueProvider.m
▸ Compiling OCMExpectationRecorder.m
▸ Compiling OCMFunctions.m
▸ Compiling OCMIndirectReturnValueProvider.m
▸ Compiling OCMInvocationExpectation.m
▸ Compiling OCMInvocationMatcher.m
▸ Compiling OCMInvocationStub.m
▸ Compiling OCMLocation.m
▸ Compiling OCMMacroState.m
▸ Compiling OCMNotificationPoster.m
▸ Compiling OCMObserverRecorder.m
▸ Compiling OCMock-dummy.m
▸ Compiling OCMockObject.m
▸ Compiling OCMPassByRefSetter.m
▸ Compiling OCMRealObjectForwarder.m
▸ Compiling OCMRecorder.m
▸ Compiling OCMReturnValueProvider.m
▸ Compiling OCMStubRecorder.m
▸ Compiling OCMVerifier.m
▸ Compiling OCObserverMockObject.m
▸ Compiling OCPartialMockObject.m
▸ Compiling OCProtocolMockObject.m
▸ Compiling OCMock_vers.c
▸ Linking OCMock
▸ Copying NSNotificationCenter+OCMAdditions.h
▸ Copying OCMConstraint.h
▸ Copying OCMFunctions.h
▸ Copying OCMLocation.h
▸ Copying OCMArg.h
▸ Copying OCMMacroState.h
▸ Copying OCMock-umbrella.h
▸ Copying OCMock.h
▸ Copying OCMockObject.h
▸ Copying OCMRecorder.h
▸ Copying OCMStubRecorder.h
▸ Touching OCMock.framework
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/OCMock/OCMock.framework
▸ Building Pods/Pods-ParseFacebookUtilsV4-UnitTests [Debug]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling Pods-ParseFacebookUtilsV4-UnitTests-dummy.m
▸ Compiling Pods_ParseFacebookUtilsV4_UnitTests_vers.c
▸ Copying Pods-ParseFacebookUtilsV4-UnitTests-umbrella.h
▸ Touching Pods_ParseFacebookUtilsV4_UnitTests.framework
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/Pods_ParseFacebookUtilsV4_UnitTests.framework
▸ Building ParseFacebookUtils/ParseFacebookUtilsV4-UnitTests [Debug]
▸ Check Dependencies
▸ Processing Info.plist
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Compiling PFFacebookTestCase.m
▸ Compiling FacebookUtilsTests.m
▸ Compiling FacebookAuthenticationProviderTests.m
▸ Linking ParseFacebookUtilsV4-UnitTests
▸ Generating 'ParseFacebookUtilsV4-UnitTests.xctest.dSYM'
▸ Running script '[CP] Copy Pods Resources'
▸ Running script '[CP] Embed Pods Frameworks'
▸ Touching ParseFacebookUtilsV4-UnitTests.xctest
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/ParseFacebookTestApplicationV4.app/PlugIns/ParseFacebookUtilsV4-UnitTests.xctest
▸ Test Succeeded
2017-09-19 10:49:15.420 xcodebuild[8704:77549]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Logs/Test/AA84B2AA-AD55-4DB1-B01A-FCF27EC39DC6/Session-ParseFacebookUtilsV4-UnitTests-2017-09-19_104915-GPK2KH.log
2017-09-19 10:49:15.420 xcodebuild[8704:77540] [MT] IDETestOperationsObserverDebug: (72BCF90F-CB53-470B-BEF0-26440E07D5E5) Beginning test session ParseFacebookUtilsV4-UnitTests-72BCF90F-CB53-470B-BEF0-26440E07D5E5 at 2017-09-19 10:49:15.420 with Xcode 8E3004b on target <DVTiPhoneSimulator: 0x7fda8ab48ae0> {
		SimDevice: SimDevice : iPhone 6 Plus (F16D1DBB-E431-424F-B390-766FF28F3391) : state={ Shutting Down } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus } runtime={ SimRuntime : 10.3.1 (14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3.1 (14E8301))
▸ Building ParseFacebookUtils/ParseFacebookUtilsV4-iOS [Debug]
▸ Check Dependencies
▸ Running script 'Fetch latest Dependencies'
▸ Running script 'Generate Localizable Strings'
▸ Compiling PFFacebookAuthenticationProvider.m
▸ Compiling PFFacebookUtils.m
▸ Compiling PFFacebookMobileAuthenticationProvider.m
▸ Compiling PFFacebookPrivateUtilities.m
▸ Touching ParseFacebookUtilsV4.framework
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/ParseFacebookUtilsV4.framework
▸ Building Pods/OCMock [Debug]
▸ Check Dependencies
▸ Compiling NSInvocation+OCMAdditions.m
▸ Compiling NSMethodSignature+OCMAdditions.m
▸ Compiling NSObject+OCMAdditions.m
▸ Compiling NSValue+OCMAdditions.m
▸ Compiling NSNotificationCenter+OCMAdditions.m
▸ Compiling OCClassMockObject.m
▸ Compiling OCMArg.m
▸ Compiling OCMArgAction.m
▸ Compiling OCMBlockArgCaller.m
▸ Compiling OCMBlockCaller.m
▸ Compiling OCMBoxedReturnValueProvider.m
▸ Compiling OCMConstraint.m
▸ Compiling OCMExceptionReturnValueProvider.m
▸ Compiling OCMExpectationRecorder.m
▸ Compiling OCMFunctions.m
▸ Compiling OCMIndirectReturnValueProvider.m
▸ Compiling OCMInvocationExpectation.m
▸ Compiling OCMInvocationMatcher.m
▸ Compiling OCMInvocationStub.m
▸ Compiling OCMLocation.m
▸ Compiling OCMMacroState.m
▸ Compiling OCMNotificationPoster.m
▸ Compiling OCMObserverRecorder.m
▸ Compiling OCMock-dummy.m
▸ Compiling OCMockObject.m
▸ Compiling OCMPassByRefSetter.m
▸ Compiling OCMRealObjectForwarder.m
▸ Compiling OCMRecorder.m
▸ Compiling OCMReturnValueProvider.m
▸ Compiling OCMStubRecorder.m
▸ Compiling OCMVerifier.m
▸ Compiling OCObserverMockObject.m
▸ Compiling OCPartialMockObject.m
▸ Compiling OCProtocolMockObject.m
▸ Compiling OCMock_vers.c
▸ Linking OCMock
▸ Touching OCMock.framework
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/OCMock/OCMock.framework
▸ Building ParseFacebookUtils/ParseFacebookTestApplicationV4 [Debug]
▸ Check Dependencies
▸ Compiling main.m
▸ Linking ParseFacebookTestApplicationV4
▸ Generating 'ParseFacebookTestApplicationV4.app.dSYM'
▸ Touching ParseFacebookTestApplicationV4.app
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/ParseFacebookTestApplicationV4.app
▸ Building Pods/Pods-ParseFacebookUtilsV4-UnitTests [Debug]
▸ Check Dependencies
▸ Compiling Pods-ParseFacebookUtilsV4-UnitTests-dummy.m
▸ Compiling Pods_ParseFacebookUtilsV4_UnitTests_vers.c
▸ Touching Pods_ParseFacebookUtilsV4_UnitTests.framework
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/Pods_ParseFacebookUtilsV4_UnitTests.framework
▸ Building ParseFacebookUtils/ParseFacebookUtilsV4-UnitTests [Debug]
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Compiling PFFacebookTestCase.m
▸ Compiling FacebookUtilsTests.m
▸ Compiling FacebookAuthenticationProviderTests.m
▸ Linking ParseFacebookUtilsV4-UnitTests
▸ Generating 'ParseFacebookUtilsV4-UnitTests.xctest.dSYM'
▸ Running script '[CP] Copy Pods Resources'
▸ Running script '[CP] Embed Pods Frameworks'
▸ Touching ParseFacebookUtilsV4-UnitTests.xctest
▸ Signing /Users/swami/Library/Developer/Xcode/DerivedData/ParseFacebookUtils-cngpgpaqpmahrxdeugxtmhqheiaz/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/ParseFacebookTestApplicationV4.app/PlugIns/ParseFacebookUtilsV4-UnitTests.xctest
▸ Test Succeeded
All tests
Test Suite ParseFacebookUtilsV4-UnitTests.xctest started
FacebookAuthenticationProviderTests
    ✓ testAuthenticateBoth (0.011 seconds)
    ✓ testAuthenticateCancel (0.009 seconds)
    ✓ testAuthenticateError (0.007 seconds)
    ✓ testAuthenticateInvalidResults (0.007 seconds)
    ✓ testAuthenticatePublish (0.007 seconds)
    ✓ testAuthenticateRead (0.005 seconds)
    ✓ testAuthType (0.001 seconds)
    ✓ testReauthenticate (0.005 seconds)
    ✓ testRestoreAuthNil (0.007 seconds)
FacebookUtilsTests
    ✓ testInitialize (0.010 seconds)
    ✓ testIsLinked (0.004 seconds)
    ✓ testLinkWithAccessToken (0.004 seconds)
    ✓ testLinkWithReadPermissions (0.004 seconds)
    ✓ testLinkWithWritePermissions (0.004 seconds)
    ✓ testLoginManager (0.001 seconds)
    ✓ testLoginReadPermissions (0.003 seconds)
    ✓ testLoginWithAccessToken (0.002 seconds)
    ✓ testLoginWritePermissions (0.003 seconds)
    ✓ testUnlink (0.003 seconds)


	 Executed 19 tests, with 0 failures (0 unexpected) in 0.097 (0.105) seconds

All tests
Test Suite ParseFacebookUtilsV4-UnitTests.xctest started
FacebookAuthenticationProviderTests
    ✓ testAuthenticateBoth (0.006 seconds)
    ✓ testAuthenticateCancel (0.005 seconds)
    ✓ testAuthenticateError (0.002 seconds)
    ✓ testAuthenticateInvalidResults (0.002 seconds)
    ✓ testAuthenticatePublish (0.002 seconds)
    ✓ testAuthenticateRead (0.002 seconds)
    ✓ testAuthType (0.001 seconds)
    ✓ testReauthenticate (0.002 seconds)
    ✓ testRestoreAuthNil (0.001 seconds)
FacebookUtilsTests
    ✓ testInitialize (0.004 seconds)
    ✓ testIsLinked (0.003 seconds)
    ✓ testLinkWithAccessToken (0.003 seconds)
    ✓ testLinkWithReadPermissions (0.003 seconds)
    ✓ testLinkWithWritePermissions (0.003 seconds)
    ✓ testLoginManager (0.001 seconds)
    ✓ testLoginReadPermissions (0.003 seconds)
    ✓ testLoginWithAccessToken (0.001 seconds)
    ✓ testLoginWritePermissions (0.003 seconds)
    ✓ testUnlink (0.003 seconds)


	 Executed 19 tests, with 0 failures (0 unexpected) in 0.049 (0.055) seconds
➜  ParseFacebookUtils-iOS git:(master) pod lib lint --use-libraries ParseFacebookUtilsV4.podspec

 -> ParseFacebookUtilsV4 (1.11.1)

ParseFacebookUtilsV4 passed validation.
➜  ParseFacebookUtils-iOS git:(master) bundle exec rake package:frameworks
▸ Cleaning ParseFacebookUtils/ParseFacebookUtilsV4-iOS [Release]
▸ Check Dependencies
▸ Clean Succeeded
▸ Building ParseFacebookUtils/ParseFacebookUtilsV4-iOS [Release]
▸ Check Dependencies
▸ Processing Info-iOS.plist
▸ Running script 'Fetch latest Dependencies'
▸ Running script 'Generate Localizable Strings'
▸ Copying ParseFacebookUtilsV4.h
▸ Copying PFFacebookUtils.h
▸ Compiling PFFacebookAuthenticationProvider.m
▸ Compiling PFFacebookUtils.m
▸ Compiling PFFacebookPrivateUtilities.m
▸ Compiling PFFacebookMobileAuthenticationProvider.m
▸ Compiling PFFacebookUtils.m
▸ Compiling PFFacebookAuthenticationProvider.m
▸ Compiling PFFacebookMobileAuthenticationProvider.m
▸ Compiling PFFacebookPrivateUtilities.m
▸ Copying Localizable.strings
▸ Touching ParseFacebookUtilsV4.framework
▸ Build Succeeded
▸ Cleaning ParseFacebookUtils/ParseFacebookUtilsV4-iOS [Release]
▸ Check Dependencies
▸ Clean Succeeded
▸ Building ParseFacebookUtils/ParseFacebookUtilsV4-iOS [Release]
▸ Check Dependencies
▸ Processing Info-iOS.plist
▸ Running script 'Fetch latest Dependencies'
▸ Running script 'Generate Localizable Strings'
▸ Copying ParseFacebookUtilsV4.h
▸ Copying PFFacebookUtils.h
▸ Compiling PFFacebookAuthenticationProvider.m
▸ Compiling PFFacebookUtils.m
▸ Compiling PFFacebookMobileAuthenticationProvider.m
▸ Compiling PFFacebookAuthenticationProvider.m
▸ Compiling PFFacebookPrivateUtilities.m
▸ Compiling PFFacebookUtils.m
▸ Compiling PFFacebookMobileAuthenticationProvider.m
▸ Compiling PFFacebookPrivateUtilities.m
▸ Copying Localizable.strings
▸ Touching ParseFacebookUtilsV4.framework
▸ Signing build/iOS/Release-ios-iphonesimulator/ParseFacebookUtilsV4.framework
▸ Build Succeeded
rm -rf /Users/swami/Documents/701Search/Parse/forked/ParseFacebookUtils-iOS/build/release/tmp
Release archive created: /Users/swami/Documents/701Search/Parse/forked/ParseFacebookUtils-iOS/build/release/ParseFacebookUtils-iOS.zip
▸ Cleaning ParseFacebookUtils/ParseFacebookUtilsV4-tvOS [Release]
▸ Check Dependencies
▸ Clean Succeeded
▸ Building ParseFacebookUtils/ParseFacebookUtilsV4-tvOS [Release]
▸ Check Dependencies
▸ Processing Info-tvOS.plist
▸ Running script 'Fetch latest Dependencies'
▸ Running script 'Generate Localizable Strings'
▸ Copying PFFacebookUtils.h
▸ Copying ParseFacebookUtilsV4.h
▸ Compiling PFFacebookDeviceAuthenticationProvider.m
▸ Compiling PFFacebookAuthenticationProvider.m
▸ Compiling PFFacebookUtils.m
▸ Compiling PFFacebookPrivateUtilities.m
▸ Copying Localizable.strings
▸ Touching ParseFacebookUtilsV4.framework
▸ Build Succeeded
▸ Cleaning ParseFacebookUtils/ParseFacebookUtilsV4-tvOS [Release]
▸ Check Dependencies
▸ Clean Succeeded
▸ Building ParseFacebookUtils/ParseFacebookUtilsV4-tvOS [Release]
▸ Check Dependencies
▸ Processing Info-tvOS.plist
▸ Running script 'Fetch latest Dependencies'
▸ Running script 'Generate Localizable Strings'
▸ Copying PFFacebookUtils.h
▸ Copying ParseFacebookUtilsV4.h
▸ Compiling PFFacebookDeviceAuthenticationProvider.m
▸ Compiling PFFacebookAuthenticationProvider.m
▸ Compiling PFFacebookUtils.m
▸ Compiling PFFacebookPrivateUtilities.m
▸ Copying Localizable.strings
▸ Touching ParseFacebookUtilsV4.framework
▸ Signing build/tvOS/Release-tvos-appletvsimulator/ParseFacebookUtilsV4.framework
▸ Build Succeeded
rm -rf /Users/swami/Documents/701Search/Parse/forked/ParseFacebookUtils-iOS/build/release/tmp
Release archive created: /Users/swami/Documents/701Search/Parse/forked/ParseFacebookUtils-iOS/build/release/ParseFacebookUtils-tvOS.zip
```


Could you please help me what I should do for the next steps?

**Comment by flovilmart** [comment]
I’ll check it out later today!

**Comment by swami701** [comment]
@flovilmart Did you have a chance to look at it? Thanks

**Comment by swami701** [comment]
@flovilmart It's passing all the checks. Can you help me to merge now?

Thank you.

**Review by flovilmart — APPROVED** [review]

**Comment by flovilmart** [comment]
Thanks @swami701!

**Comment by swami701** [comment]
Thanks @flovilmart Just curious, will the latest master code be available in cocoapod? if not can you release the latest master branch. I saw the last release was on Feb 2016.

**Comment by flovilmart** [comment]
YES i’ll Build a release today!

**Pull request merged**
