### PR TITLE
Updates podspec for 1.11.2 release

### PR DESCRIPTION
**Pull request by natanrolnik**
@flovilmart a new release will silent the warning described in #83.

The change is already in master, we just need a new version.

### CODE REVIEW

**Comment by flovilmart** [comment]
@natanrolnik can you bump the Parse framework, Bolts and the min target?

**Comment by natanrolnik** [comment]
Weird, I remember I did those, just forgot to push probably.

**Comment by tealshift** [comment]
Is this pull request solving the problem causing my CocoaPods to reject Parse version 1.16.0?

[!] Unable to satisfy the following requirements:                                                                              
- `Parse (= 1.16.0)` required by `Podfile`                                    
- `Parse` required by `Podfile`                                               
- `Parse (~> 1.15.1)` required by `ParseFacebookUtilsV4 (1.11.2)`

**Comment by flovilmart** [comment]
@tealshift ParseFacebookUtilsV4 is now part of the Parse SDK when you use cocoapods.

Just add the `pod 'Parse/FacebookUtils'` to your podfile and you should be fine.

**Comment by tealshift** [comment]
@flovilmart Thanks! That made Pods happy. Unfortunately it breaks my swift module imports for this somehow. (I know this isn't the place to talk about linking frameworks. Wish I could DM you here.)

**Pull request closed without merging**
